### ISSUE TITLE
Github git updates

### ISSUE THREAD

**Issue by K2AAE** [db4ple/mchf-github#2]
I'm trying to learn git and discovered how to get my local clone HD git in sync but the github git is still behind and the convoluted Git Pro docs are killing me. When I checked the forks of others I found most github forks are not up to date, your git being the exception.  sp9bsl github is behind too.
How do you keep your github git in sync?  

Note: The naming conventions on the data sheets seems kind of redundant: Directory/folder datasheet tells us that what is in the directory/folder is a datasheet so why add DATASHEET_ to the name of a file in the datasheet folder? Just my opinion but it is a little redundant. 
One thing that should be is when downloading a datasheet from the vendor they sometimes use in house document numbers instead of the actual name: en.DM00273119.pdf which I rename to STM32F76xZIT.pdf but I believe there are other language versions you might want to look at including.

**Comment by db4ple** [comment]
Hi Kevin,
it is important to understand how git and GitHub works. I don't if this helps but linked the slide set I use to explain how we work with Git & GitHub in the UHSDR project. You will see that the only person who can update your GitHub repository is you, and that this requires you to update your local repository first if you follow our approach. This is how GitHub works, there is no direct "update" operation.  There is a way to do  it without a local repository: Create a pull request for your own repository using the UHSDR repo as source for changes and merge your own change request via GitHub. That does the job as well but then your local git repository is still not up-to-date. Which is more important than the public GitHub unless you want to contribute at which moment it becomes the means to send your changes to someone else. Before that, there is no need to keep the GitHub repo in sync.  
 
   
[3 (!) Repositories make up a proper github.pdf](https://github.com/db4ple/mchf-github/files/1395419/3.Repositories.make.up.a.proper.github.pdf)

**Comment by K2AAE** [comment]
Thanks! I started to explain this in the Wiki with setting up a Windows build environment but still need to figure a few things out: 

Say A is DF8OE master, B and C are Contributors. B and C are working on the same file, in the Git Documentation it shows B and C getting the code in sync and after the code is in sync then issuing a pull for that branch.  
In your PDF slide show you have B going to A 'push' then C going to A 'fetch' then C 'pushing' to C git then A going to C git 'pull' then B going to A 'fetch'.  

Can your PDF be added to the documentation? That would have saved me a couple of hours! 

I think I get the 'I' have to manually update the fork git thing from my local HD but I haven't got that part working back to the fork github part, yet, your github fork is up to date.
My command line in my local git directory:
git remote add upstream https://github.com/df8oe/UHSDR.git 
then 
git fetch upstream
Updated my Local HD 
Funny thing is Github Desktop (Windows app) can't see the updates!
Thanks! I started to explain this in the Wiki with setting up a Windows build environment but still need to figure a few things out: 

Say A is DF8OE master, B and C are Contributors. B and C are working on the same file, in the Git Documentation it shows B and C getting the code in sync and after the code is in sync then issuing a pull for that branch.  
In your PDF slide show you have B going to A 'push' then C going to A 'fetch' then C 'pushing' to C git then A going to C git 'pull' then B going to A 'fetch'.  

Can your PDF be added to the documentation? That would have saved me a couple of hours! 
I think I get the 'I' have to manually update the fork git thing from my local HD but I haven't got that part working back to the fork github part, yet, your github fork is up to date.
My command line in my local git directory:
git remote add upstream https://github.com/df8oe/UHSDR.git 
then 
git fetch upstream
Updated my Local HD 
Funny thing is Github Desktop (Windows app) can't see the updates!

I did a git pull on my forked git and it said I'm up to day with my local but I'm not.
"Create a pull request for your own repository using the UHSDR repo as source for changes and merge your own change request via GitHub."
  How do you do that from the local command line?

**Comment by db4ple** [comment]
Hi Kevin,
it seems you pasted some content twice, please cleanup a bit and I'll try to answer. 

BTW, yes you can use the link to the PDF in the issue above as link in the wiki. For whatever reason adding a file to an issue seems the easiest way to "upload" files for use in the wiki.

**Comment by K2AAE** [comment]
Thanks again! 

I think I get the 'I' have to manually update the fork git thing from my local HD but I haven't got that part working back to the fork github part, yet, your github fork is up to date.
My command line in my local git directory:
git remote add upstream https://github.com/df8oe/UHSDR.git
then
git fetch upstream
Updated my Local HD
Funny thing is Github Desktop (Windows app) can't see the updates!

I started to explain this in the Wiki with setting up a Windows build environment but still need to figure a few things out:

Say A is DF8OE master, B and C are Contributors. B and C are working on the same file, in the Git Documentation it shows B and C getting the code in sync and after the code is in sync then issuing a pull for that branch from A.
In your PDF slide show you have B going to A 'push' then C going to A 'fetch' then C 'pushing' to C git then A going to C git 'pull' then B going to A 'fetch'.

I did a git pull on my forked git at github from my local HD command line and it said I'm up to date with my local but I'm not since my local shows the latest from master/A/DF8OE.

"Create a pull request for your own repository using the UHSDR repo as source for changes and merge your own change request via GitHub."
How do you do that from the local command line? Or are you talking about my fork git to DF8OE?

That was confusing, the double must have happened when I copied the post to my notepad and later thought I was Ctrl+V'ing the USDR URL..

**Comment by db4ple** [comment]
What git pull does depends to which tracking branch your local branch is connected to. 
git pull with no further arguments "pulls"  from the defined tracking branch into your local branch (the one you have currently checked out.
So if you see the changes of DF8OE but your GitHub doesn't have them and still git pull says everything up-to-date, your remote tracking branch is the branch of DF8OE (or one which is identical to this) but not your GitHub branch.  So much for remote diagnosis. 
You can run `git branch -vv` which will list all your branches, mark the branch you ar currently working on and will tell you the upstream/tracking branch in square brackets for each branch setup with a upstream branch in a remote repository. 

You cannot create a GitHub Pull Request from the local command line. Locally you push your changes to your GitHub Repo and only from there you can create a pull request. The concept of a pull request is not known to git, this is a concept from GitHub.

**Comment by K2AAE** [comment]
For some reason I thought Github was git.... (git-scm.com) I installed 17.04 and setup the git, the Help system works on linux for git, days of reading:
 "Note in the example that we set up a triangular workflow, where we pull from one location and push to another." 
Thanks

**Comment by K2AAE** [comment]
Update: Github Desktop replied, in the Current Branch drop down I have to select upstream/active-devel then use the Fetch origin Icon to sync DF8OE active-devel to my fork of DF8OE active-devel in my git. Now when I visit https://github.com/k2aae my git shows me up to date with DF8OE active-devel.
It only takes a second to get the git updated now.
I'll add this to the Wiki
